version: "3"
services:
  notebook:
      image: jupyter/datascience-notebook:latest
      container_name: jupyter
      volumes:
        - ./notebooks:/home/jovyan/work
      ports:
        - 8888:8888
